//! Asset request specification for LLM‑driven asset pipeline contract.

use crate::error::{ValidationErrors, error_buffer};
use crate::push_validation_error;
use crate::{ArchetypeTag, FailureClass, SemanticArtifact, TerrainType, Versioned};
use serde::{Deserialize, Serialize};
use std::fmt;

// Byte limits for text fields
const MAX_STYLE_CONTEXT_BYTES: usize = 200;
const MAX_PROMPT_CORE_BYTES: usize = 600;

// ---------------------------------------------------------------------------
// AssetRequestSpec – LLM → deterministic asset pipeline contract
// ---------------------------------------------------------------------------

/// Typed request authored by LLM-facing graphics tooling.
///
/// This is semantic input only. Deterministic pipeline stages enrich this
/// request with a style suffix and composed full prompt downstream.
///
/// - `prompt_core`: The base prompt describing the asset geometry and structure.
/// - `style_context`: Art direction context that influences the visual style.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AssetRequestSpec {
    /// The family/category of asset being requested.
    pub asset_family: AssetRequestFamily,
    /// The archetype tag identifying this specific asset type.
    pub archetype_tag: ArchetypeTag,
    /// The biome context for styling the asset, if applicable.
    pub biome_context: Option<TerrainType>,
    /// Art direction context that influences the visual style.
    pub style_context: String,
    /// The base prompt describing the asset geometry and structure.
    pub prompt_core: String,
    /// Quality level hint for generation.
    pub quality_hint: Option<AssetRequestQualityHint>,
    /// Source hint indicating how the asset was created.
    pub source_hint: Option<AssetRequestSourceHint>,
}

// ---------------------------------------------------------------------------
// Asset enums
// ---------------------------------------------------------------------------

/// The family/category of asset being requested.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum AssetRequestFamily {
    /// Major landmark asset.
    HeroLandmark,
    /// Modular building components.
    ArchitectureKit,
    /// Plant life and foliage.
    Vegetation,
    /// Decorative objects.
    Prop,
    /// Terrain surface details.
    TerrainDetail,
    /// Surface decals/textures.
    Decal,
}

/// Quality level hint for asset generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum AssetRequestQualityHint {
    /// Low quality, for testing.
    Draft,
    /// Full quality, for production.
    Production,
    /// Unknown quality level.
    #[serde(other)]
    Unknown,
}

/// Source hint indicating how the asset was created.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum AssetRequestSourceHint {
    /// Manually created by an artist.
    HandAuthored,
    /// Generated by AI.
    AiGenerated,
    /// Acquired from a third-party source.
    Purchased,
    /// Unknown source.
    #[serde(other)]
    Unknown,
}

// ---------------------------------------------------------------------------
// Display implementations for enums
// ---------------------------------------------------------------------------

impl fmt::Display for AssetRequestFamily {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            AssetRequestFamily::HeroLandmark => write!(f, "hero_landmark"),
            AssetRequestFamily::ArchitectureKit => write!(f, "architecture_kit"),
            AssetRequestFamily::Vegetation => write!(f, "vegetation"),
            AssetRequestFamily::Prop => write!(f, "prop"),
            AssetRequestFamily::TerrainDetail => write!(f, "terrain_detail"),
            AssetRequestFamily::Decal => write!(f, "decal"),
        }
    }
}

impl fmt::Display for AssetRequestQualityHint {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            AssetRequestQualityHint::Draft => write!(f, "draft"),
            AssetRequestQualityHint::Production => write!(f, "production"),
            AssetRequestQualityHint::Unknown => write!(f, "unknown"),
        }
    }
}

impl fmt::Display for AssetRequestSourceHint {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            AssetRequestSourceHint::HandAuthored => write!(f, "hand_authored"),
            AssetRequestSourceHint::AiGenerated => write!(f, "ai_generated"),
            AssetRequestSourceHint::Purchased => write!(f, "purchased"),
            AssetRequestSourceHint::Unknown => write!(f, "unknown"),
        }
    }
}

// ---------------------------------------------------------------------------
// Trait implementations
// ---------------------------------------------------------------------------

impl Versioned for AssetRequestSpec {
    fn version(&self) -> u32 {
        1
    }
    fn artifact_type_name(&self) -> &'static str {
        "AssetRequestSpec"
    }
}

// ---------------------------------------------------------------------------
// AssetRequestSpecBuilder – fluent API for constructing AssetRequestSpec
// ---------------------------------------------------------------------------

/// Builder for [`AssetRequestSpec`] with fluent API.
#[derive(Debug, Default)]
pub struct AssetRequestSpecBuilder {
    /// The asset family to set.
    asset_family: Option<AssetRequestFamily>,
    /// The archetype tag to set.
    archetype_tag: Option<ArchetypeTag>,
    /// The biome context to set.
    biome_context: Option<Option<TerrainType>>,
    /// The style context to set.
    style_context: Option<String>,
    /// The prompt core to set.
    prompt_core: Option<String>,
    /// The quality hint to set.
    quality_hint: Option<Option<AssetRequestQualityHint>>,
    /// The source hint to set.
    source_hint: Option<Option<AssetRequestSourceHint>>,
}

/// Error type for `AssetRequestSpecBuilder::try_build`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BuildError {
    /// A required field was not set before calling `try_build()`.
    MissingField(&'static str),
}

impl BuildError {
    /// Create a new error for a missing required field.
    pub fn missing(field: &'static str) -> Self {
        Self::MissingField(field)
    }
}

impl std::fmt::Display for BuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BuildError::MissingField(field) => write!(f, "missing required field: {}", field),
        }
    }
}

impl std::error::Error for BuildError {}

impl AssetRequestSpecBuilder {
    /// Create a new empty builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the asset family.
    pub fn asset_family(mut self, value: AssetRequestFamily) -> Self {
        self.asset_family = Some(value);
        self
    }

    /// Set the archetype tag.
    pub fn archetype_tag(mut self, value: ArchetypeTag) -> Self {
        self.archetype_tag = Some(value);
        self
    }

    /// Set the biome context. Use `None` for no biome context.
    pub fn biome_context(mut self, value: Option<TerrainType>) -> Self {
        self.biome_context = Some(value);
        self
    }

    /// Set the style context from any string-like value.
    pub fn style_context(mut self, value: impl Into<String>) -> Self {
        self.style_context = Some(value.into());
        self
    }

    /// Set the prompt core from any string-like value.
    pub fn prompt_core(mut self, value: impl Into<String>) -> Self {
        self.prompt_core = Some(value.into());
        self
    }

    /// Set the quality hint. Use `None` for no quality hint.
    pub fn quality_hint(mut self, value: Option<AssetRequestQualityHint>) -> Self {
        self.quality_hint = Some(value);
        self
    }

    /// Set the source hint. Use `None` for no source hint.
    pub fn source_hint(mut self, value: Option<AssetRequestSourceHint>) -> Self {
        self.source_hint = Some(value);
        self
    }

    /// Build the [`AssetRequestSpec`], returning an error if any required field is not set.
    pub fn try_build(self) -> Result<AssetRequestSpec, BuildError> {
        Ok(AssetRequestSpec {
            asset_family: self.asset_family.ok_or(BuildError::missing("asset_family"))?,
            archetype_tag: self.archetype_tag.ok_or(BuildError::missing("archetype_tag"))?,
            biome_context: self.biome_context.unwrap_or(None),
            style_context: self.style_context.ok_or(BuildError::missing("style_context"))?,
            prompt_core: self.prompt_core.ok_or(BuildError::missing("prompt_core"))?,
            quality_hint: self.quality_hint.unwrap_or(None),
            source_hint: self.source_hint.unwrap_or(None),
        })
    }

    /// Build the [`AssetRequestSpec`].
    ///
    /// # Panics
    /// Panics if any required field is not set.
    ///
    /// # Deprecated
    /// Use `try_build` instead to handle missing fields gracefully.
    #[deprecated = "Use try_build() instead"]
    #[allow(clippy::expect_used)]
    pub fn build(self) -> AssetRequestSpec {
        self.try_build().expect("AssetRequestSpecBuilder: missing required fields")
    }
}

impl AssetRequestSpec {
    /// Create a new builder for [`AssetRequestSpec`].
    pub fn builder() -> AssetRequestSpecBuilder {
        AssetRequestSpecBuilder::new()
    }
}

impl SemanticArtifact for AssetRequestSpec {
    fn validate(&self) -> ValidationErrors {
        let mut errors = error_buffer();

        let style = self.style_context.trim();
        let prompt = self.prompt_core.trim();

        // Validate style_context bounds (E012 empty, E016 overflow)
        if style.is_empty() {
            push_validation_error!(
                errors,
                FailureClass::Semantic,
                "E012",
                self.artifact_type_name(),
                "style_context",
                style.to_owned(),
                "style_context cannot be empty"
            );
        }
        if style.len() > MAX_STYLE_CONTEXT_BYTES {
            push_validation_error!(
                errors,
                FailureClass::Semantic,
                "E016",
                self.artifact_type_name(),
                "style_context",
                format!("{} bytes", style.len()),
                format!("style_context exceeds {} bytes", MAX_STYLE_CONTEXT_BYTES)
            );
        }

        // Validate prompt_core bounds (E013 empty, E014 overflow)
        if prompt.is_empty() {
            push_validation_error!(
                errors,
                FailureClass::Semantic,
                "E013",
                self.artifact_type_name(),
                "prompt_core",
                prompt.to_owned(),
                "prompt_core cannot be empty"
            );
        }
        if prompt.len() > MAX_PROMPT_CORE_BYTES {
            push_validation_error!(
                errors,
                FailureClass::Semantic,
                "E014",
                self.artifact_type_name(),
                "prompt_core",
                format!("{} bytes", prompt.len()),
                format!("prompt_core exceeds {} bytes", MAX_PROMPT_CORE_BYTES)
            );
        }

        // Check for control-character injection (E018, E019)
        let has_control = |s: &str| s.chars().any(|c| c.is_control() && c != '\n' && c != '\t');
        if has_control(prompt) {
            push_validation_error!(
                errors,
                FailureClass::Semantic,
                "E018",
                self.artifact_type_name(),
                "prompt_core",
                prompt.to_owned(),
                "prompt_core contains prohibited control characters"
            );
        }
        if has_control(style) {
            push_validation_error!(
                errors,
                FailureClass::Semantic,
                "E019",
                self.artifact_type_name(),
                "style_context",
                style.to_owned(),
                "style_context contains prohibited control characters"
            );
        }

        // Check for unknown variants (E017)
        if let Some(ref quality) = self.quality_hint
            && matches!(quality, AssetRequestQualityHint::Unknown)
        {
            push_validation_error!(
                errors,
                FailureClass::Semantic,
                "E017",
                self.artifact_type_name(),
                "quality_hint",
                format!("{}", quality),
                "unknown variant encountered; update the schema",
                warning
            );
        }
        if let Some(ref source) = self.source_hint
            && matches!(source, AssetRequestSourceHint::Unknown)
        {
            push_validation_error!(
                errors,
                FailureClass::Semantic,
                "E017",
                self.artifact_type_name(),
                "source_hint",
                format!("{}", source),
                "unknown variant encountered; update the schema",
                warning
            );
        }

        errors
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn valid_spec() -> AssetRequestSpec {
        AssetRequestSpec {
            asset_family: AssetRequestFamily::HeroLandmark,
            archetype_tag: ArchetypeTag::new("highlands_watchtower").expect("valid tag"),
            biome_context: Some(TerrainType::Highlands),
            style_context: "northern weathered stone".to_string(),
            prompt_core: "broken watchtower with collapsed upper ring and mossy foundation"
                .to_string(),
            quality_hint: Some(AssetRequestQualityHint::Production),
            source_hint: Some(AssetRequestSourceHint::AiGenerated),
        }
    }

    #[test]
    fn valid_spec_passes() {
        let spec = valid_spec();
        assert_eq!(spec.version(), 1);
        assert!(spec.validate().is_empty());
    }

    #[test]
    fn empty_prompt_core_fails() {
        let mut spec = valid_spec();
        spec.prompt_core = "   ".to_string();
        let errors = spec.validate();
        assert!(!errors.is_empty());
        let msg = errors[0].to_string();
        assert!(msg.contains("prompt_core cannot be empty"));
    }

    #[test]
    fn empty_style_context_fails() {
        let mut spec = valid_spec();
        spec.style_context = String::new();
        let errors = spec.validate();
        assert!(!errors.is_empty());
        let msg = errors[0].to_string();
        assert!(msg.contains("style_context cannot be empty"));
    }

    #[test]
    fn prompt_core_at_boundary() {
        // Exactly 600 bytes should pass ("x" is 1 byte, so 600 "x" chars = 600 bytes)
        let spec = AssetRequestSpec {
            asset_family: AssetRequestFamily::HeroLandmark,
            archetype_tag: ArchetypeTag::new("test_tag").expect("valid tag"),
            biome_context: Some(TerrainType::Highlands),
            style_context: "test".to_string(),
            prompt_core: "x".repeat(600),
            quality_hint: Some(AssetRequestQualityHint::Production),
            source_hint: Some(AssetRequestSourceHint::AiGenerated),
        };
        assert!(spec.validate().is_empty());

        // 601 bytes should fail
        let mut spec = valid_spec();
        spec.prompt_core = "x".repeat(601);
        let errors = spec.validate();
        assert!(!errors.is_empty());
        let msg = errors[0].to_string();
        assert!(msg.contains("prompt_core exceeds 600 bytes"));
    }

    #[test]
    fn style_context_at_boundary() {
        // Exactly 200 bytes should pass ("x" is 1 byte, so 200 "x" chars = 200 bytes)
        let spec = AssetRequestSpec {
            asset_family: AssetRequestFamily::HeroLandmark,
            archetype_tag: ArchetypeTag::new("test_tag").expect("valid tag"),
            biome_context: Some(TerrainType::Highlands),
            style_context: "x".repeat(200),
            prompt_core: "test prompt".to_string(),
            quality_hint: Some(AssetRequestQualityHint::Production),
            source_hint: Some(AssetRequestSourceHint::AiGenerated),
        };
        assert!(spec.validate().is_empty());

        // 201 bytes should fail
        let mut spec = valid_spec();
        spec.style_context = "x".repeat(201);
        let errors = spec.validate();
        assert!(!errors.is_empty());
        let msg = errors[0].to_string();
        assert!(msg.contains("style_context exceeds 200 bytes"));
    }

    #[test]
    fn missing_tag_is_valid() {
        let tag = ArchetypeTag::missing();
        assert_eq!(tag.as_str(), "missing");
        // missing() tag should be creatable and valid
        assert!(ArchetypeTag::new("missing").is_ok());
    }

    #[test]
    fn missing_tag_in_spec_passes() {
        // A spec with the "missing" archetype tag should be valid
        let spec = AssetRequestSpec {
            asset_family: AssetRequestFamily::Prop,
            archetype_tag: ArchetypeTag::new("missing").expect("valid missing tag"),
            biome_context: None,
            style_context: "simple".to_string(),
            prompt_core: "a simple prop".to_string(),
            quality_hint: None,
            source_hint: None,
        };
        assert!(spec.validate().is_empty());
    }

    #[test]
    fn roundtrip_serialization() {
        let spec = valid_spec();
        let json = serde_json::to_string(&spec).expect("serialize spec");
        let decoded: AssetRequestSpec = serde_json::from_str(&json).expect("deserialize spec");
        assert_eq!(decoded, spec);
    }

    #[test]
    fn unknown_quality_hint_is_warning() {
        // Unknown quality hint should produce a warning, not an error
        let spec = AssetRequestSpec {
            asset_family: AssetRequestFamily::HeroLandmark,
            archetype_tag: ArchetypeTag::new("test_tag").expect("valid tag"),
            biome_context: Some(TerrainType::Highlands),
            style_context: "test style".to_string(),
            prompt_core: "test prompt".to_string(),
            quality_hint: Some(AssetRequestQualityHint::Unknown),
            source_hint: Some(AssetRequestSourceHint::AiGenerated),
        };
        let errors = spec.validate();
        assert!(!errors.is_empty());
        assert!(errors[0].is_warning());
        assert!(errors[0].to_string().contains("E017"));
    }

    #[test]
    fn control_char_rejected() {
        // Control characters (except \n and \t) should be rejected in prompt_core (E018)
        let spec = AssetRequestSpec {
            asset_family: AssetRequestFamily::HeroLandmark,
            archetype_tag: ArchetypeTag::new("test_tag").expect("valid tag"),
            biome_context: Some(TerrainType::Highlands),
            style_context: "test style".to_string(),
            prompt_core: "test\x00prompt".to_string(), // null byte
            quality_hint: Some(AssetRequestQualityHint::Production),
            source_hint: Some(AssetRequestSourceHint::AiGenerated),
        };
        let errors = spec.validate();
        assert!(!errors.is_empty());
        let msg = errors[0].to_string();
        assert!(msg.contains("E018") || msg.contains("control characters"));

        // Also test style_context with control char (E019)
        let spec = AssetRequestSpec {
            asset_family: AssetRequestFamily::HeroLandmark,
            archetype_tag: ArchetypeTag::new("test_tag").expect("valid tag"),
            biome_context: Some(TerrainType::Highlands),
            style_context: "test\x01style".to_string(), // SOH character
            prompt_core: "test prompt".to_string(),
            quality_hint: Some(AssetRequestQualityHint::Production),
            source_hint: Some(AssetRequestSourceHint::AiGenerated),
        };
        let errors = spec.validate();
        assert!(!errors.is_empty());
        let msg = errors[0].to_string();
        assert!(msg.contains("E019") || msg.contains("control characters"));
    }

    #[test]
    fn multi_byte_boundary() {
        // Test with multi-byte UTF-8 characters (e.g., emoji are 4 bytes each)
        // 200 bytes limit for style_context: 50 emoji = 200 bytes exactly
        let emoji = "🎨"; // 4 bytes
        let spec = AssetRequestSpec {
            asset_family: AssetRequestFamily::HeroLandmark,
            archetype_tag: ArchetypeTag::new("test_tag").expect("valid tag"),
            biome_context: Some(TerrainType::Highlands),
            style_context: emoji.repeat(50), // 50 * 4 = 200 bytes
            prompt_core: "test".to_string(),
            quality_hint: Some(AssetRequestQualityHint::Production),
            source_hint: Some(AssetRequestSourceHint::AiGenerated),
        };
        assert!(spec.validate().is_empty());

        // 51 emoji = 204 bytes exceeds 200 limit
        let mut spec = spec;
        spec.style_context = emoji.repeat(51);
        let errors = spec.validate();
        assert!(!errors.is_empty());
        assert!(errors[0].to_string().contains("200 bytes"));
    }

    #[test]
    fn builder_roundtrip() {
        let spec = AssetRequestSpec::builder()
            .asset_family(AssetRequestFamily::HeroLandmark)
            .archetype_tag(ArchetypeTag::new("test_builder").expect("valid tag"))
            .biome_context(Some(TerrainType::Highlands))
            .style_context("builder style")
            .prompt_core("builder prompt")
            .quality_hint(Some(AssetRequestQualityHint::Production))
            .source_hint(Some(AssetRequestSourceHint::HandAuthored))
            .try_build()
            .expect("builder should have all required fields");

        assert_eq!(spec.asset_family, AssetRequestFamily::HeroLandmark);
        assert_eq!(spec.archetype_tag.as_str(), "test_builder");
        assert_eq!(spec.biome_context, Some(TerrainType::Highlands));
        assert_eq!(spec.style_context, "builder style");
        assert_eq!(spec.prompt_core, "builder prompt");
        assert_eq!(spec.quality_hint, Some(AssetRequestQualityHint::Production));
        assert_eq!(spec.source_hint, Some(AssetRequestSourceHint::HandAuthored));
        assert!(spec.validate().is_empty());
    }
}
